name: Hello World
on: push
jobs:
  hello-job:
    name: hello-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Echo text
        run: echo "Hello, world!"
